name       : gufw
version    : 16.04.0
release    : 1
source     :
    - https://launchpad.net/gui-ufw/16.04/16.04/+download/gui-ufw-16.04.0.tar.gz : 6e3bb97e26ebb7027a792bd598ad249096c4f2d5d26f7a74e74acadf613e0434
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
description: |
    GUFW GUI interface for UFW Firewall
rundeps    :
    - ufw
    - python-netifaces
builddeps  :
    - python-distutils-extra
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
