name       : gufw
version    : 20.04.1
release    : 16
source     :
    - https://github.com/costales/gufw/releases/download/20.04.1/gufw-20.04.1.tar.gz : bc09f67796325b2e1ea4ac2c3c541f5c6eab7aa4510f77fcd7b0a506f1e57fd8
homepage   : https://costales.github.io/projects/gufw/
license    : GPL-3.0-or-later
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python3-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python3-gobject
    - ufw
setup      : |
    %python3_setup
install    : |
    %python3_install
