name       : gufw
version    : 21.04.0
release    : 21
source     :
    - https://github.com/costales/gufw/archive/21.04.0.tar.gz : b57892ec9817ca1520b2fef31cc3ef404b243ef1230bdccfdc6d75ed4e461841
homepage   : https://costales.github.io/projects/gufw/
license    : GPL-3.0-or-later
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python-gobject
    - ufw
setup      : |
    %patch -p1 < $pkgfiles/fix-gufw-pkexec.patch
    %python3_setup
install    : |
    %python3_install
