name       : gufw
version    : 18.04.0
release    : 9
source     :
    - https://launchpad.net/gui-ufw/trunk/18.04/+download/gui-ufw-18.04.0.tar.gz : b6b12524d3d2c6035288f15003c97aa23eef862fdaa78fb621e045cd793374fc
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python3-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python3-gobject
    - ufw
setup      : |
    # Note this is especially named to stand out that it needs updating from stack updates
    %patch -p1 < $pkgfiles/0001-Update-path-from-python3.5-to-python3.6.patch
    %python3_setup
install    : |
    %python3_install
