name       : gufw
version    : 19.10.0
release    : 14
source     :
    - https://launchpad.net/gui-ufw/trunk/19.10/+download/gui-ufw-19.10.0.tar.gz : 18c155ef7b62e457e7c89fb9827db531a453d3fd766911c1b09c9fc716255cba
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python3-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python3-gobject
    - ufw
setup      : |
    # Note this is especially named to stand out that it needs updating from stack updates
    %patch -p1 < $pkgfiles/0001-Update-path-from-python3.5-to-python3.6.patch
    %python3_setup
install    : |
    %python3_install
