name       : gufw
version    : 18.10.0
release    : 11
source     :
    - https://launchpad.net/gui-ufw/trunk/18.10/+download/gui-ufw-18.10.0.tar.gz : c44468550cbcb35ebee0dd8339341447118811ccd0714e79350136117421b93b
license    : GPL-3.0-or-later
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python3-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python3-gobject
    - ufw
setup      : |
    %python3_setup
install    : |
    %python3_install
