name       : gufw
version    : 15.10.0
release    : 1
source     :
    - https://launchpad.net/gui-ufw/15.10/15.10/+download/gui-ufw-15.10.0.tar.gz : 58fee07bc33f9be615e899b943535ca8755fdf9262010c2580a0176d2a1c2443
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
description: |
    GUFW GUI interface for UFW Firewall
builddeps  :
    - python-distutils-extra
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
