name       : gufw
version    : 17.10.0
release    : 6
source     :
    - https://launchpad.net/gui-ufw/trunk/17.10/+download/gui-ufw-17.10.0.tar.gz : 8632e763a07e8057f312786b8f7c4970d44c26e73f8b184be1d2fc314e9c3dac
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    One of the easiest firewalls in the world! A very friendly graphical user interface to manage UFW (Uncomplicated FireWall).
builddeps  :
    - pkgconfig(gtk+-3.0)
    - python-distutils-extra
    - python3-gobject-devel # T3904
rundeps    :
    - libwebkit-gtk
    - python3-gobject
    - ufw
setup      : |
    %patch -p1 < $pkgfiles/0001-gufw-pkexec-lib-lib64.patch
    python3 setup.py build
install    : |
    python3 setup.py install --root="%installroot%"
