name       : gufw
version    : 17.04.1
release    : 2
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+files/gui-ufw_17.04.1.orig.tar.gz : fd933242f14514167f14a72fc452a2a76767c6f1ca795835b642719d0fa27c38
license    : GPL-3.0
summary    : GUFW GUI interface for UFW Firewall
component  : security
description: |
    GUFW GUI interface for UFW Firewall
builddeps  :
    - python-distutils-extra
rundeps    :
    - ufw
    - python-netifaces
build      : |
    %python_setup
install    : |
    %python_install
